services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # 你的数据库密码
      MYSQL_DATABASE: ${DB_NAME}     # 自动创建数据库
    volumes:
      - mysql-data:/var/lib/mysql
      - ./createEmployee.sql:/docker-entrypoint-initdb.d/init.sql
      #挂载到 /docker-entrypoint-initdb.d/ 会自动执行这个 SQL 文件，仅在第一次初始化容器时。


    ports:
      - "3306:3306"
    networks:
      - app-net

  redis:
    image:  redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-net

  backend:
    build: ./springboot
    container_name: springboot
    ports:
      - "8080:8080"
    env_file:
      - .env  # 可以省略，Compose 默认读取当前目录的 .env
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    healthcheck: #健康测试
      test: ["CMD","curl","-f","http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - app-net

  frontend:
    build: ./vue-project
    container_name: frontend #改名了
    ports:
#      - "8081:80" #本地测试使用
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy #只有当 springboot 健康才启动前端
    networks:
      - app-net

networks:
  app-net:

volumes:
  mysql-data:  # 定义mysql-data卷
#    external: true  # 使用外部卷，而不是 Compose 自动创建的卷
    external: false
  redis-data:
    external: false
