#本地开发环境
server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:?Please set the JWT_SECRET environment variable}
  access-token-expiration: ${JWT_ACCESS_EXP:900000}     # 15分钟 = 15*60*1000
  refresh-token-expiration: ${JWT_REFRESH_EXP:604800000} # 7天

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}


# 配置mybatis实体和xml映射
mybatis:
  ## 映射xml
  ##在classpath（recources）路径下，有个mapper包，里面有xml文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启下划线to驼峰转换,数据库字段使用下划线命名
    map-underscore-to-camel-case: true
